### ISSUE TITLE
Won't show in server version 3.1 (does on desktop)

### ISSUE THREAD

**Issue by tommandt** [yianni-ververis/SenseUI-BarChart#2]
Are you planning on any updates - we love the extension

**Comment by yianni-ververis** [comment]
What type of updates are you looking for?

**Comment by tommandt** [comment]
2 things - (1) we are trying to print it and it shows up blank - not all extensions do, but yours does. 
(2)  Shows invalid visualization with server 3.1, seems to work with desktop 3.1

Again - we are addicted to the extension, so keeping it working with new sense versions will be important to us.  Thanks

**Comment by yianni-ververis** [comment]
Nice to see that you are using it. Most of our horizontal bars  in webapps.qlik.com are made with this. 

i have not tested the printing because we are using it for web only. Will do more tests.

Regarding the 3.1 server, I will test it now since I do not have any issues so far.

The upcoming is this to also be a vertical bar chart

**Comment by yianni-ververis** [comment]
@tommandt please do F12 and send me the error messages you get from the console tab

**Comment by tommandt** [comment]
I misunderstood our programmer - it was a different issue we had with Server.  Our main issue with this is that it doesn't print (we get a blank screen whether we try to print the page or we include it in a story and then print (pdf or ppt) the story..  Is that a function of all extensions or is there something you or we can do to make that work?  Thanks

**Comment by tommandt** [comment]
Now I just loaded Sense 3.1SR2 update and get the invalid visualization.  Do you get notified of point revisions to try?

**Comment by yianni-ververis** [comment]
I have 3.1SR2 on my system without any issues. Can you take a screenshot of the console?

**Comment by tommandt** [comment]
Here is the message in IE single configurator

[image: pasted1]

Here it is in desktop

[image: pasted2]
here is my local extensions

[image: pasted3]

**Comment by yianni-ververis** [comment]
can you send them to yianni.ververis@qlik.com?

**Comment by Wolfgang33** [comment]
I have the same problem with Desktop V 3.1 SR3.
Error message:
Ungültige Visualisierung
Die Visualisierung wurde auf dem Server nicht gefunden:
senseui-barchart

Same message with Sense-UI-Drop-Down

**Comment by yianni-ververis** [comment]
Please hold on shft+ctrl+right mouse click and go to Console. Let me know what the error says or take a screenshot

**Comment by Wolfgang33** [comment]
Error message in console:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:4848/resources/assets/core/utils/theme.js??1478781641535

Von: Yianni Ververis [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Januar 2017 18:40
An: yianni-ververis/SenseUI-BarChart <SenseUI-BarChart@noreply.github.com>
Cc: Wolfgang Stratenwerth <wolfgang.stratenwerth@smart-compliance.biz>; Comment <comment@noreply.github.com>
Betreff: Re: [yianni-ververis/SenseUI-BarChart] Won't show in server version 3.1 (does on desktop) (#2)


Please hold on shft+ctrl+right mouse click and go to Console. Let me know what the error says or take a screenshot

**Comment by yianni-ververis** [comment]
This error is because the Theme folder has moved from 3.1.2 and above. I explain this to all of my other extensions that are using the core Theme.

The problem is that this extension does not use the theme palette!

What other extensions are you using?

**Comment by Wolfgang33** [comment]
I use several extensions, but the error only occurs when I try to drag a SenseUI-BarChart or SenseUI-DropDown visualization to my worksheet. All other visualizations are working well.

Here the list:

-        Climber Custom Report

-        DateRangePicker

-        measureBuilder

-        Reload Button

-        Sheet Navigation & Actions

-        Simple KPI

-        SVG Reader

-        Variable

-        Word Cloud
[cid:image001.jpg@01D27303.0FA89BD0]


Von: Yianni Ververis [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Januar 2017 19:04
An: yianni-ververis/SenseUI-BarChart <SenseUI-BarChart@noreply.github.com>
Cc: Wolfgang Stratenwerth <wolfgang.stratenwerth@smart-compliance.biz>; Comment <comment@noreply.github.com>
Betreff: Re: [yianni-ververis/SenseUI-BarChart] Won't show in server version 3.1 (does on desktop) (#2)


This error is because the Theme folder has moved from 3.1.2 and above. I explain this to all of my other extensions that are using the core Theme.

The problem is that this extension does not use the theme palette!

What other extensions are you using?

**Comment by yianni-ververis** [comment]
Are you using the latest version, 2.0.2? Maybe I used it in he past....

It should say in the console which version it is

**Comment by Wolfgang33** [comment]
Sorry, I can’t find version information at the console.
I downloaded the actual zip-file from https://github.com/yianni-ververis/SenseUI-BarChart.
In the zip-file the file senseui-barchart.js (date: 09.12.2016) contains version info 1.2.
File senseui-barchart.qext contains version info 1.0
File d3.min .js contains version 3.5.17
File bower.json contains:
{
  "name": "SenseUI-BarChart",
  "version": "0.1",
  "ignore": [
    "**/.*",
    "libs"
  ],
  "dependencies": {
    "d3": "~3.5.14",
    "d3-tip": "~0.6.7"
  },
  "resolutions": {
    "d3": "~3.5.14"
  }
}


Von: Yianni Ververis [mailto:notifications@github.com]
Gesendet: Freitag, 20. Januar 2017 12:23
An: yianni-ververis/SenseUI-BarChart <SenseUI-BarChart@noreply.github.com>
Cc: Wolfgang Stratenwerth <wolfgang.stratenwerth@smart-compliance.biz>; Comment <comment@noreply.github.com>
Betreff: Re: [yianni-ververis/SenseUI-BarChart] Won't show in server version 3.1 (does on desktop) (#2)


Are you using the latest version, 2.0.2? Maybe I used it in he past....

It should say in the console which version it is

**Comment by yianni-ververis** [comment]
I just updeated bower to reflect the latest version.

Your console should have a message like this

![image](https://cloud.githubusercontent.com/assets/12610095/22150340/80f8a6f0-dee6-11e6-83da-525996968f21.png)

**Comment by Wolfgang33** [comment]
Sorry,

I press shift+ctrl + right-mouse-button, then choose “Show DevTools”.
Within DevTools I select Tab “Console”. No version, see pic:
[cid:image002.jpg@01D27326.6EE7EB50]

Von: Yianni Ververis [mailto:notifications@github.com]
Gesendet: Freitag, 20. Januar 2017 14:01
An: yianni-ververis/SenseUI-BarChart <SenseUI-BarChart@noreply.github.com>
Cc: Wolfgang Stratenwerth <wolfgang.stratenwerth@smart-compliance.biz>; Comment <comment@noreply.github.com>
Betreff: Re: [yianni-ververis/SenseUI-BarChart] Won't show in server version 3.1 (does on desktop) (#2)


I just updeated bower to reflect the latest version.

Your console should have a message like this

[image]<https://cloud.githubusercontent.com/assets/12610095/22150340/80f8a6f0-dee6-11e6-83da-525996968f21.png>

**Comment by yianni-ververis** [comment]
once in console hit F5. You should see something like this
![image](https://cloud.githubusercontent.com/assets/12610095/22150684/7650d1b2-dee8-11e6-8c0a-2907f6285bba.png)

Also, go to Network and disable cache
![image](https://cloud.githubusercontent.com/assets/12610095/22150700/8c78489e-dee8-11e6-9104-65f691b21d9a.png)

then hit F5 again

**Comment by Wolfgang33** [comment]
Thanks!
The Cache was the problem.
Now everything works well.
Fantastic support!
Von: Yianni Ververis [mailto:notifications@github.com]
Gesendet: Freitag, 20. Januar 2017 14:15
An: yianni-ververis/SenseUI-BarChart <SenseUI-BarChart@noreply.github.com>
Cc: Wolfgang Stratenwerth <wolfgang.stratenwerth@smart-compliance.biz>; Comment <comment@noreply.github.com>
Betreff: Re: [yianni-ververis/SenseUI-BarChart] Won't show in server version 3.1 (does on desktop) (#2)


once in console hit F5. You should see something like this
[image]<https://cloud.githubusercontent.com/assets/12610095/22150684/7650d1b2-dee8-11e6-8c0a-2907f6285bba.png>

Also, go to Network and disable cache
[image]<https://cloud.githubusercontent.com/assets/12610095/22150700/8c78489e-dee8-11e6-9104-65f691b21d9a.png>

then hit F5 again

**Comment by yianni-ververis** [comment]
I am glad that everything worked.

Yianni
