### ISSUE TITLE
Problem with latest version of Qlik Sense

### ISSUE THREAD

**Issue by STondreauOnGit** [yianni-ververis/SenseUI-BarChart#5]
Hi Yanni,
Your extension looks amazing. Unfortunately, I am using QlikSense 3.2 Server and only the "General" category appears with just a few properties. Any suggestions ?
Thanks for any advice,
Stephane

**Comment by yianni-ververis** [comment]
Can you open the console and  let me know the error you are getting?

Its working fine on June and September 2017 releases

**Comment by STondreauOnGit** [comment]
Hi Yanni,
It seems to be related to IE because it looks fine when I try it in Chrome.
Are you aware of any reason why IE would cause issues ? A lot of my user community is using IE.
Thanks for any light you can shed on this,
Stephane

**Comment by STondreauOnGit** [comment]
Hi Yanni,
It all seems fine in Chrome. Amazing extension!
Quick question: Could this be used for vertical barcharts ?

**Comment by yianni-ververis** [comment]
Yeah this is kinda obsolete, I have the latest version in a library with many more charts. I just do not have time to finalize and publish it.

Thank you for using it
